---
resource_types:
- name: gcs
  type: registry-image
  source:
    repository: frodenas/gcs-resource

resources:
- name: pxf_src
  type: git
  source:
    branch: update-pg-regress
    uri: {{pxf-git-remote}}
    private_key: ((ccp-git-key))

- name: gpdb6_rhel7_rpm_latest-0
  type: gcs
  icon: google-drive
  source:
    bucket: data-gpdb-ud-pivnet-artifacts
    json_key: ((pxf-storage-service-account-key))
    regexp: latest-0_gpdb6/greenplum-db-(.*)-rhel7-x86_64.rpm

- name: gpdb6-pxf-dev-centos7-image
  type: registry-image
  source:
    repository: gcr.io/data-gpdb-ud/gpdb-pxf-dev/gpdb6-centos7-test-pxf
    tag: latest
    username: _json_key
    password: ((pxf-cloudbuild-service-account-key))

- name: gpdb6-pxf-dev-centos7-hdp2-server
  type: registry-image
  source:
    repository: gcr.io/data-gpdb-ud/gpdb-pxf-dev/gpdb6-centos7-test-pxf-hdp2
    tag: latest
    username: _json_key
    password: ((pxf-cloudbuild-service-account-key))

- name: pxf-build-dependencies
  type: gcs
  icon: google-drive
  source:
    bucket: data-gpdb-ud-pxf-build-resources
    json_key: ((pxf-storage-service-account-key))
    versioned_file: build-dependencies/pxf-build-dependencies.tar.gz

- name: pxf_tarball
  type: s3
  source:
    access_key_id: {{bucket-access-key-id}}
    bucket: {{pxf-aws-bucket-name}}
    region_name: {{aws-region}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: pxf_artifacts/((folder-prefix))_((gpdb-branch))/latest/pxf-gp6.el7.tar.gz

jobs:

- name: compile_pxf
  plan:
  - in_parallel:
    - get: pxf_src
      trigger: true
    - get: gpdb_package
      resource: gpdb6_rhel7_rpm_latest-0
    - get: pxf-build-dependencies
    - get: gpdb6-pxf-dev-centos7-image
  - task: build_pxf
    image: gpdb6-pxf-dev-centos7-image
    file: pxf_src/concourse/tasks/build.yml
    params:
      LICENSE: ((pxf-rpm-license))
      VENDOR: ((pxf-rpm-vendor))
      FDW: true
  - put: pxf_tarball
    params:
      file: dist/pxf-gp*.el7.tar.gz

- name: test_pxf
  plan:
  - in_parallel:
    - get: pxf_src
      passed:
      - compile_pxf
      trigger: true
    - get: pxf_tarball
      passed:
      - compile_pxf
      trigger: true
    - get: gpdb_package
      resource: gpdb6_rhel7_rpm_latest-0
      passed:
        - compile_pxf
    - get: gpdb6-pxf-dev-centos7-hdp2-server
  - task: test_pxf
    file: pxf_src/concourse/tasks/test.yml
    image: gpdb6-pxf-dev-centos7-hdp2-server
    params:
      GROUP: fdw_smoke_schedule
      HADOOP_CLIENT: HDP
      IMPERSONATION: true
      PGPORT: {{pgport}}
      PG_REGRESS: true
      GP_VER: 6

- name: test_pxf_s3
  plan:
  - in_parallel:
    - get: pxf_src
      passed:
      - compile_pxf
      trigger: true
    - get: pxf_tarball
      passed:
      - compile_pxf
      trigger: true
    - get: gpdb_package
      resource: gpdb6_rhel7_rpm_latest-0
      passed:
        - compile_pxf
    - get: gpdb6-pxf-dev-centos7-hdp2-server
  - task: test_pxf
    attempts: 2
    file: pxf_src/concourse/tasks/test.yml
    image: gpdb6-pxf-dev-centos7-hdp2-server
    params:
      ACCESS_KEY_ID: {{tf-machine-access-key-id}}
      GROUP: fdw_hcfs_schedule
      HADOOP_CLIENT: HDP
      IMPERSONATION: true
      PGPORT: {{pgport}}
      PG_REGRESS: true
      GP_VER: 6
      PROTOCOL: s3
      SECRET_ACCESS_KEY: {{tf-machine-secret-access-key}}

- name: test_pxf_gcs
  plan:
  - in_parallel:
    - get: pxf_src
      passed:
      - compile_pxf
      trigger: true
    - get: pxf_tarball
      passed:
      - compile_pxf
      trigger: true
    - get: gpdb_package
      resource: gpdb6_rhel7_rpm_latest-0
      passed:
        - compile_pxf
    - get: gpdb6-pxf-dev-centos7-hdp2-server
  - task: test_pxf
    attempts: 2
    file: pxf_src/concourse/tasks/test.yml
    image: gpdb6-pxf-dev-centos7-hdp2-server
    params:
      ACCESS_KEY_ID: {{tf-machine-access-key-id}}
      GOOGLE_CREDENTIALS: {{data-gpdb-ud-google-json-key}}
      GROUP: fdw_hcfs_schedule
      HADOOP_CLIENT: HDP
      IMPERSONATION: true
      PGPORT: {{pgport}}
      PG_REGRESS: true
      GP_VER: 6
      PROTOCOL: gs

- name: test_pxf_wasbs
  plan:
  - in_parallel:
    - get: pxf_src
      passed:
      - compile_pxf
      trigger: true
    - get: pxf_tarball
      passed:
      - compile_pxf
      trigger: true
    - get: gpdb_package
      resource: gpdb6_rhel7_rpm_latest-0
      passed:
        - compile_pxf
    - get: gpdb6-pxf-dev-centos7-hdp2-server
  - task: test_pxf
    attempts: 2
    file: pxf_src/concourse/tasks/test.yml
    image: gpdb6-pxf-dev-centos7-hdp2-server
    params:
      ACCESS_KEY_ID: {{tf-machine-access-key-id}}
      GROUP: fdw_hcfs_schedule
      HADOOP_CLIENT: HDP
      IMPERSONATION: true
      PGPORT: {{pgport}}
      PG_REGRESS: true
      GP_VER: 6
      PROTOCOL: wasbs
      WASBS_ACCOUNT_KEY: {{wasb-account-key}}
      WASBS_ACCOUNT_NAME: {{wasb-account-name}}

- name: test_pxf_adl
  plan:
  - in_parallel:
    - get: pxf_src
      passed:
      - compile_pxf
      trigger: true
    - get: pxf_tarball
      passed:
      - compile_pxf
      trigger: true
    - get: gpdb_package
      resource: gpdb6_rhel7_rpm_latest-0
      passed:
        - compile_pxf
    - get: gpdb6-pxf-dev-centos7-hdp2-server
  - task: test_pxf
    attempts: 2
    file: pxf_src/concourse/tasks/test.yml
    image: gpdb6-pxf-dev-centos7-hdp2-server
    params:
      ADL_ACCOUNT: {{adl-account}}
      ADL_OAUTH2_CLIENT_ID: {{adl-client-id}}
      ADL_OAUTH2_CREDENTIAL: {{adl-credential}}
      ADL_OAUTH2_REFRESH_URL: {{adl-refresh-url}}
      GROUP: fdw_hcfs_schedule
      HADOOP_CLIENT: HDP
      IMPERSONATION: true
      PGPORT: {{pgport}}
      PG_REGRESS: true
      GP_VER: 6
      PROTOCOL: adl

- name: test_pxf_minio
  plan:
  - in_parallel:
    - get: pxf_src
      passed:
      - compile_pxf
      trigger: true
    - get: pxf_tarball
      passed:
      - compile_pxf
      trigger: true
    - get: gpdb_package
      resource: gpdb6_rhel7_rpm_latest-0
      passed:
        - compile_pxf
    - get: gpdb6-pxf-dev-centos7-hdp2-server
  - task: test_pxf
    file: pxf_src/concourse/tasks/test.yml
    image: gpdb6-pxf-dev-centos7-hdp2-server
    params:
      GROUP: fdw_hcfs_schedule
      IMPERSONATION: false
      PGPORT: {{pgport}}
      PG_REGRESS: true
      GP_VER: 6
      PROTOCOL: minio
